name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - '**/Dockerfile'
      - '**/*.py'
      - 'docker-compose.yml'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx (allows for more advanced builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to the GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/backup-webhook:${{ github.sha }} .

      # Push the Docker image to GitHub Container Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/backup-webhook:${{ github.sha }}

      # Optionally, tag the image as 'latest' if it's from the 'main' branch
      - name: Tag and Push 'latest' image
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/backup-webhook:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/backup-webhook:latest
          docker push ghcr.io/${{ github.repository_owner }}/backup-webhook:latest
